### ISSUE TITLE
PO marked as sent even if checkbox is checked for review, and final send wasn't done

### ISSUE THREAD

**Issue by scottcwilson** [DivaVocals/zen_DropShipPO#4]
I started working on this but didn't finish it in case anyone else wants to look.  You can see where I stopped the setting here: 

https://github.com/DivaVocals/zen_DropShipPO/pull/1/commits/c7228715fe9294d6e84ca95f8a15f11891c4cb7e

But I wasn't able to figure out how to set it once the send was actually done.

**Comment by scottcwilson** [comment]
I have a fix for this but I want my client to do more testing prior to creating a PR - see 
https://github.com/scottcwilson/zen_DropShipPO/tree/FIXES_4
She will be able to test after 06/06/16 and I will let you know then.

**Comment by DivaVocals** [comment]
Scott you are the BEST!!
